version: "3"
services:
  web_thirdblogwsl:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3004:3000"
    volumes: 
      - ./thirdblogwsl:/opt/app
      - gem_cache_thirdblogwsl:/gems
    env_file: 
      - .env/development/database_thirdblogwsl
      - .env/development/web_thirdblogwsl
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_thirdblogwsl
    networks:
      - network
  webpack_dev_server_thirdblogwsl:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "4004:4004"
    volumes: 
      - ./thirdblogwsl:/opt/app
      - gem_cache_thirdblogwsl:/gems
    env_file: 
      - .env/development/database_thirdblogwsl
      - .env/development/web_thirdblogwsl
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_thirdblogwsl:
    image: postgres
    env_file: 
      - .env/development/database_thirdblogwsl
    volumes: 
      - db_data_thirdblogwsl:/var/lib/postgresql/data
    networks:
      - network
volumes: 
  db_data_thirdblogwsl:
  gem_cache_thirdblogwsl:
networks:
  network: